#The version is commented as it's obsolete in docker v4.30.0, but it can be enabled if necessary to run on older versions of docker.
#version: "3.3"

services:
  apache:
    build: apacheconf
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html
    links:
      - mysql:mysql
  mysql:
    build: mysqlconf
    restart: unless-stopped
    volumes:
      - ./databases:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"      
  phpmyadmin:
    build: phpmyadminconf
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
